"""create tables

Revision ID: d5c1fce30ec3
Revises: 
Create Date: 2023-06-14 10:51:40.234862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c1fce30ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentinels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soldiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sentinelId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sentinelId'], ['sentinels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scoutId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scoutId'], ['scouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('soldierId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['soldierId'], ['soldiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('observations')
    op.drop_table('alarms')
    op.drop_table('soldiers')
    op.drop_table('sentinels')
    op.drop_table('scouts')
    op.drop_table('teams')
    op.drop_table('users')
    # ### end Alembic commands ###
